---
platform: linux

inputs:
- name: config
- name: env
- name: files
- name: vars # variable files to be made available
  optional: true
- name: secrets
  # secret files to be made available
  # separate from vars, so they can be store securely
  optional: true

params:
  NAME:
  CONFIG_FILE: product.yml
  ENV_FILE: env.yml
  OPSMAN_SSH_PRIVATE_KEY:
  VARS_FILES:
  # - Optional
  # - Filepath to the Ops Manager vars yaml file
  # - The path is relative to root of the task build,
  #   so `vars` and `secrets` can be used.

run:
  file: proposed-tasks/apply-runtime-config.sh
